### ISSUE TITLE
Cards on home page

### ISSUE THREAD

**Issue by VaibhavVermaa16** [avinash201199/MemeGenerator#14]
Meme cards shown on the home page are not so interactive and animations are not so good. Also the whole div moves while hovering on a single card.
I would like to work on them please assign it to me

**Comment by Shu12388y** [comment]
@VaibhavVermaa16 start working on it

**Comment by VaibhavVermaa16** [comment]
i am a bit confused about which file to work on, can you please guide me

**Comment by Sanjeev12357** [comment]
This issue is also resolved

**Comment by Shu12388y** [comment]
@Sanjeev12357 start working

**Comment by Sanjeev12357** [comment]
issue fixed

**Comment by Sanjeev12357** [comment]
this issue is also resolved sir
