### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by Shu12388y** [avinash201199/MemeGenerator#15]
![WhatsApp Image 2023-10-24 at 2 30 17 PM](https://github.com/avinash201199/MemeGenerator/assets/91714143/806e60d0-5b49-45c7-8f06-deafd4a0b94d)

**Comment by Sanjeev12357** [comment]
I would like to work on this sir

**Comment by Ayush-kathayat** [comment]
Sir can you assigned this to me i would like to work on this

**Comment by Sanjeev12357** [comment]
sir please assign..

**Comment by Shu12388y** [comment]
@Ayush-kathayat start working

**Comment by Sanjeev12357** [comment]
@Shu12388y Sir, please give me a chance too, I commented first.

**Comment by Ayush-kathayat** [comment]
thanks sir for assigning this to me i will start working on this right away

**Comment by Ayush-kathayat** [comment]
sir before working on this i think i  need to work on a new issue ( feature adding )

ADDING CSS VARIABLES  ( for breakpoints , colors  , margin , and padding )

Sure, here are the benefits of using CSS variables in a more concise format:

1. Maintainability: CSS variables ensure consistency across the project and make the CSS easier to maintain.
2. Dynamic Values: CSS variables can be updated in real-time in the browser, allowing for dynamic and interactive styling.
3. Scope Control: CSS variables can be globally or locally scoped, providing more control over where they can be used.
4. Readability: CSS variables can make the CSS code more readable and easier to understand.
5. Reduced Repetition:  CSS variables can reduce repetition in the CSS code by allowing values to be defined once and reused throughout the stylesheet.

**Comment by Sanjeev12357** [comment]
@Shu12388y  Sir can i do this?
