### ISSUE TITLE
Adding Github Link to the website

### ISSUE THREAD

**Issue by thanmaisai** [avinash201199/MemeGenerator#16]
I noticed that there is no direct link to the GitHub repository associated with the project on the website.
 
 Describe the Bug:
There is currently no GitHub link available on the website.

To Reproduce:
1. Visit the website.
2. Look for a direct link to the GitHub repository.

Expected Behavior:
I expect to find a visible and easily accessible link to the GitHub repository on the website.

![Screenshot 2023-10-25 at 12 24 56 AM](https://github.com/avinash201199/MemeGenerator/assets/91474486/3014b89b-432e-4936-85f9-e877987bc321)

**Comment by thanmaisai** [comment]
Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for hacktoberfest 2023 and OSEN open source program.

**Comment by Shu12388y** [comment]
@thanmaisai start working
