### ISSUE TITLE
[ FEATURE REQUEST ] Implement CSS Variables for Improved Styling and Maintainability

### ISSUE THREAD

**Issue by Ayush-kathayat** [avinash201199/MemeGenerator#17]
Hello,

I propose that we start using CSS variables in our project for the following reasons:

1. **Maintainability**: CSS variables will make our stylesheets easier to maintain. If we need to change a value, we only need to update it in one place, and the change will be reflected everywhere the variable is used.

2. **Dynamic Values**: CSS variables are live in the browser and can be updated in real-time. This will allow us to create more dynamic and interactive styling, such as changing themes or adjusting styles based on user interaction.

3. **Scope Control**: With CSS variables, we can control the scope of our variables. We can define global variables that will be accessible throughout our entire stylesheet, or we can define variables within specific selectors to limit their scope.

4. **Readability**: By giving meaningful names to our variables, we can make our CSS code more readable and easier to understand. This will be particularly beneficial when collaborating on this project.

5. **Reduced Repetition**: CSS variables will help us reduce repetition in our CSS code. Instead of repeating the same values over and over, we can define them once as a variable and then reuse that variable throughout our stylesheet.

Here is an example of how we can define and use a CSS variable:

```css
:root {
  --primary-color: #0076c6;
}

body {
  background-color: var(--primary-color);
}
```

In this example, `--primary-color` is a global variable that is defined in the `:root` selector. It is then used as the background color for the body. If we want to change the primary color, we only need to update the `--primary-color` variable.

I believe that implementing CSS variables will greatly improve our development process and the quality of our code. I would be happy to take on this task and start implementing CSS variables in our project. 

Could you please assign this issue to me?

Thank you.

**Comment by Shu12388y** [comment]
@Ayush-kathayat start working
