### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by anmolmalik01** [avinash201199/MemeGenerator#33]
As a designer, I think the website is lacking when it comes to design, so if it's possible I can show you the Figma design to redesign the website.

**Comment by Shu12388y** [comment]
@anmolmalik01 start working

**Comment by anmolmalik01** [comment]
Sir, I have come up with this design, 
- **If any changes are required, that can be made**
- I **will provide full animations, design, and visualization** if this is selected. The work can then be divided between interested collaborators

![Screenshot from 2023-10-28 00-23-11](https://github.com/avinash201199/MemeGenerator/assets/69298609/a7a11bc8-d5e4-467f-91dd-e5f2c156c376)
![Screenshot from 2023-10-28 00-23-16](https://github.com/avinash201199/MemeGenerator/assets/69298609/55fdda42-3e07-4a7b-9267-543e0285f1c1)
