### ISSUE TITLE
Responsiveness of the website

### ISSUE THREAD

**Issue by Shu12388y** [avinash201199/MemeGenerator#37]
![Screenshot from 2023-10-27 09-52-21](https://github.com/avinash201199/MemeGenerator/assets/91714143/bdcc394d-b101-4dd6-8d41-826bfbc8da1d)

**Comment by Sanjeev12357** [comment]
Please assign me this sir

**Comment by Shu12388y** [comment]
@Sanjeev12357 start working

**Comment by Sanjeev12357** [comment]
issue fixed
