### ISSUE TITLE
Modify the scroller

### ISSUE THREAD

**Issue by Shu12388y** [avinash201199/MemeGenerator#43]
change the scoll bar

![Screenshot (99)](https://github.com/avinash201199/MemeGenerator/assets/91714143/7a30e518-c9db-4829-9042-603b70de3515)

**Comment by Sanjeev12357** [comment]
I would like to do this sir

**Comment by Shu12388y** [comment]
@Sanjeev12357 start working

**Comment by Sanjeev12357** [comment]
Issue fixed
