### ISSUE TITLE
Add Routing

### ISSUE THREAD

**Issue by Shu12388y** [avinash201199/MemeGenerator#6]

**Comment by Sanjeev12357** [comment]
what kind of routing do you want sir can you please elaborate as i can see the cards are working fine when i click on them it opens perfectly fine.

**Comment by Shu12388y** [comment]
There will be home route and meme route as you see in the website when we click on a meme we can not go back to the home page

**Comment by Sanjeev12357** [comment]
okk

**Comment by Sanjeev12357** [comment]
Routing added sir please assign me the task to make it responsive
