### ISSUE TITLE
Add search Bar

### ISSUE THREAD

**Issue by Shu12388y** [avinash201199/MemeGenerator#7]

**Comment by ritik48** [comment]
@Shu12388y please assign this issue to me

**Comment by Shu12388y** [comment]
@ritik48 start working on the issue

**Comment by Sanjeev12357** [comment]
please assign me this sir

**Comment by Sanjeev12357** [comment]
can i also work on this sir?

**Comment by Sanjeev12357** [comment]
@Shu12388y sir??

**Comment by Shu12388y** [comment]
@Sanjeev12357 start working

**Comment by Sanjeev12357** [comment]
I have added the search bar sir , also there is an api error coming cors error i dont know how to resolve it i have added the pr for it you can check

**Comment by Sanjeev12357** [comment]
In the mean time i would like to work on the responsivness of the project

**Comment by Sanjeev12357** [comment]
Search bar created sir

**Comment by Sanjeev12357** [comment]
You can check please assign me the task to make this responsive in the mean time
